PanDAWMS/dkb

Utils/Dataflow/README
Stages 011, 012 were united into 015. The modifcation is already
finished, but the README wasn't updated.
=> DF: update README: Stage 15 is finished.

Utils/Dataflow/055_documents2TTL/documents2ttl.py
pyDKB has been integrated with documents2ttl module 
on 055 stage for processing input stream|files.
=> pyDKB integration for input data processing

Utils/Dataflow/015_CDSDocuments/getCDSDocuments.py
Bug fixes:
* ignored function input parameter
* failure due to the missed JSON field
=> Stage 015 (CDS documents) bug fixes

Utils/Dataflow/015_CDSDocuments/getCDSDocuments.py
* New command line parameters:
```
USAGE
./getCDSPapers.py <options> [file]
ARGUMENTS
file                    Input file name (default: Input/list_of_papers.json)
OPTIONS
-o, --output-dir DIR    Output directory name
```
=> Stage 015 (CDS Documents)

README, Utils/Elasticsearch/get_aggregated_data_from_bigpanda.php, Utils/Elasticsearch/get_data_for_hashtags.php, Utils/Elasticsearch/load_data.php, Utils/Elasticsearch/process.sh
Added set of scripts for getting aggregated data from bigpanda and storing it to elasticsearch
=> Aggregated to es

Utils/Dataflow/015_CDSDocuments/getCDSDocuments.py, Utils/Dataflow/015_CDSDocuments/input
Stage 015 now works through pyDKB Stage interface.
---
The PR waits the completion of #22, and will be rebased on `dataflow-with-document-content` branch after #22 is merged.
=> Stage 015 (CDS documents) with pyDKB

Utils/Dataflow/030_PDFAnalyzer/manager.py
Better representation of export statistics and some minor fixes.
pyDKB related update will follow when this pull request will be proccessed.
=> Stage 030 statistics update

Utils/Dataflow/030_PDFAnalyzer/flow.py, Utils/Dataflow/030_PDFAnalyzer/manager.py, Utils/Dataflow/030_PDFAnalyzer/pdfwork.py, Utils/Dataflow/030_PDFAnalyzer/xmltable.py
It is a rebased version of #39.
The original request is to be used to continue the work on PEP-8.
This request is to be updated when all the requested changes are done and commited to the original one and then merged.
=> Stage 030 PEP-8 (rebased version)

Utils/Dataflow/030_PDFAnalyzer/manager.py
Update contains:
1. Option to extract dataset IDs only from tables.
2. Removal of "possible year" cluttering exported papers.
3. Export error fix.
4. ~~New script for adding hashtags to papers.~~
=> Stage 030 dataset IDs update

Utils/Elasticsearch/.gitignore, Utils/Elasticsearch/Oracle2JSON.py, Utils/Elasticsearch/process.sh, Utils/Elasticsearch/query/mc16_campaign_for_ES.sql
Add possibility to get "updated" data from Oracle.
As we need this functionality "as soon as possible", we can\`t use Kafka JDBC connector to handle this.
But hopefully we\`ll do it later.
Or make it a standard way for Dataflow connectors, to accept the `--offset` parameter and handle it within the scripts.
To run the scripts via cron:
* use properly defined base dir instead of `.` (current dir)
* run with `sh -l` to avoid missing env variables defined in `/etc/profile.d/`
Also, some minor fixes:
* handling of ';' -- strip it away instead of cutting the last character
* check for data imported from Oracle before doing the convertation and load
* PEP-8 fixes
=> Ora2ES: SQL query with timestamp condition

Utils/Dataflow/069_upload2es/README, Utils/Dataflow/069_upload2es/load_data.sh, Utils/Elasticsearch/process.sh, Utils/Elasticsearch/tools/load_data.sh
Left to do:
The added items are decided to be taken care of outside the script (in the manager program like Kafka app or in the mediator code, as in `dataflow-ora2es-test`)
=> Stage 069: upload2es

Utils/Dataflow/009_oracleConnector/Oracle2JSON.py
Bug fixes:
* config file operations would fail since 071d66c41a5631332fb05e10823e89ea70861a13
Improvements:
* fix duplicate output
Refactoring:
* separate data (semantic) transformation and output from record squashing/joining
=> Stage 09 oracle connector enhance

Utils/Dataflow/030_PDFAnalyzer/flow.py
Changes:
* fix exit code generation (in case of an error, program must return non-zero code);
* in case of error the traceback of the exception goes to STDERR with mark `(ERROR)`.
=> Stage 030: runtime exception handling

Utils/Dataflow/000_kafka/config/log4j.properties, Utils/Dataflow/000_kafka/config/topology.properties, Utils/Dataflow/000_kafka/ru/kiae/dkb/kafka/common/external/ExternalProcessLogger.java, Utils/Dataflow/000_kafka/ru/kiae/dkb/kafka/connect/external/sink/ExternalProcessWriter.java, Utils/Dataflow/000_kafka/ru/kiae/dkb/kafka/connect/external/source/ExternalProcessQuerier.java, Utils/Dataflow/000_kafka/ru/kiae/dkb/kafka/streams/processor/external/ExternalProcessorConfig.java, Utils/Dataflow/000_kafka/ru/kiae/dkb/kafka/streams/processor/external/ExternalProcessorSupplier.java, Utils/Dataflow/000_kafka/run-class.sh, Utils/Dataflow/000_kafka/run.sh, Utils/Dataflow/000_kafka/runStreamsApplication.sh
Main changes:
* external process` STDERR monitoring added (it goes to standard logger);
* ExternalProcessor adapter is now aware about failures in the external process...
* ...and know what to do on the failure (retry policies added);
* fixed issue with empty messages from the ext. process (single EOP marker);
* an attempt to solve issue #45 (yet requires more efforts);
* logging improved:
* accurate logfile name detection;
* log file size limit raised to 1M;
* timing logger added.
=> Kafka Dataflow enhancement

Utils/Dataflow/000_kafka/config/010-glance-lop-source.properties, Utils/Dataflow/000_kafka/config/015-application.properties, Utils/Dataflow/000_kafka/config/015-topology.properties, Utils/Dataflow/000_kafka/config/054-application.properties, Utils/Dataflow/000_kafka/config/054-topology.properties, Utils/Dataflow/000_kafka/config/055-application.properties, Utils/Dataflow/000_kafka/config/055-topology.properties, Utils/Dataflow/000_kafka/config/060-virtuoso-ttl-sink.properties, Utils/Dataflow/000_kafka/run.sh
Main changes:
* configured chains for document metadata transfer/mining (Stages 10,15,18,30,54,55);
* fixed poll interval for Glance connector;
* `run.sh` now allows to run all known chains/connectors at once.
=> Dataflow configuration

Utils/Dataflow/055_documents2TTL/documents2ttl.py
Fix issue with abstract extraction.
=> Stage 055 (document2TTL) fix

Utils/Dataflow/run/.gitignore, Utils/Dataflow/run/ora2es.sh
Shell script to chain stages, related to the data flow from Oracle to Elasticsearch.
=> Dataflow ora2es chain

Utils/Dataflow/069_upload2es/load_data.sh
=> Stage 069 (upload2es) update

Utils/Dataflow/009_oracleConnector/Oracle2JSON.py
Fixed according to review comments for PR #54.
Fixes:
* exit in case of missed cx_Oracle;
* exit in case of failed connection attempt;
* unused function and variable removed;
* category detection improved.
=> Stage 09: fix

Utils/Dataflow/pyDKB/__init__.py, Utils/Dataflow/pyDKB/common/exceptions.py, Utils/Dataflow/pyDKB/common/hdfs.py, Utils/Dataflow/pyDKB/dataflow/cds.py, Utils/Dataflow/pyDKB/dataflow/dkbID.py, Utils/Dataflow/pyDKB/dataflow/messages.py, Utils/Dataflow/pyDKB/dataflow/stage/AbstractProcessorStage.py, Utils/Dataflow/pyDKB/dataflow/stage/AbstractStage.py, Utils/Dataflow/pyDKB/dataflow/stage/processors.py
Reverts PanDAWMS/dkb#71
...for wrong pyDKB version in the description.
=> Revert "pyDKB 2.0"

.travis.yml, Utils/Dataflow/009_oracleConnector/Oracle2JSON.py
To run Python syntax check in parallel with PEP8 check, we added both
checks to the sama stage.
=> Travis: add Python syntax check.

Utils/Dataflow/030_PDFAnalyzer/manager.py, Utils/Dataflow/030_PDFAnalyzer/pdfwork.py, Utils/Dataflow/030_PDFAnalyzer/xmltable.py
Fixed two issues discovered by pycodestyle.
=> Stage 030 pycodestyle

Utils/Dataflow/009_oracleConnector/Oracle2JSON.py, Utils/Dataflow/009_oracleConnector/dbConnection.py
Adding possibility to load data in a backward direction, moving deeper into the past with every step.
Main changes:
* reverse data load introduced (initiated by corredponding parameters in `timestamps` section:
* `final` < `initial`,
* `step` < 0.
Minor changes:
* code refactoring;
* improved config parameters handling (verification, default values, etc.).
=> Stage 009: reverse data load

Utils/Dataflow/pyDKB/dataflow/stage/ProcessorStage.py
Main changes:
* `__out_files()` method is splitted into a number of smaller methods:
* `get_ot_dir()`;
* `get_out_filename()`;
* `get_out_file_info()`;
* code was refactored for better readability;
* added some additional checks before using `hdfs.movefile()` for better handling of possible errors.
=> [pending] [stack] pyDKB development (pt.6): refactoring and minor improvement of ProcessorStage output files functionality.

Utils/Dataflow/pyDKB/dataflow/stage/AbstractProcessorStage.py, Utils/Dataflow/pyDKB/dataflow/stage/AbstractStage.py, Utils/Dataflow/pyDKB/dataflow/stage/__init__.py, Utils/Dataflow/pyDKB/dataflow/types.py
Logging added in the simpliest possible way -- as a method of parent class for Stages.
It would definitely be better to use some independant "logger" to avoid re-implementation of this method in any other class and for the library as a whole, but it is left for the future (see #91).
=> [stack] pyDKB development (pt.1): unified logging for Stages.

Utils/Dataflow/pyDKB/common/hdfs.py, Utils/Dataflow/pyDKB/dataflow/stage/AbstractProcessorStage.py
Main changes:
* added `path` functionality (using `posixpath` for HDFS-related actions);
* added `File()` function (to simplify work with temporary local copy of HDFS files);
* added `movefile()` function (to simplify writing output files to HDFS).
=> [stack] pyDKB development (pt.2): improve HDFS module

Utils/Dataflow/pyDKB/dataflow/messages.py, Utils/Dataflow/pyDKB/dataflow/stage/AbstractProcessorStage.py
Fixed:
* last output file was never moved to HDFS;
* missed logic step in output file definition;
* typo in docstring.
=> [stack] pyDKB development (pt.3): fixes

Utils/Dataflow/015_CDSDocuments/getCDSDocuments.py, Utils/Dataflow/016_task2es/task2es.py, Utils/Dataflow/018_PDFDownloader/getPDFfromCDS.py, Utils/Dataflow/091_datasetsRucio/datasets_processing.py, Utils/Dataflow/093_datasetsFormat/datasets_format.py, Utils/Dataflow/095_datasetInfoAMI/amiDatasets.py, Utils/Dataflow/pyDKB/dataflow/stage/AbstractProcessorStage.py, Utils/Dataflow/pyDKB/dataflow/stage/AbstractStage.py, Utils/Dataflow/pyDKB/dataflow/stage/ProcessorStage.py, Utils/Dataflow/pyDKB/dataflow/stage/__init__.py, Utils/Dataflow/skel/stage.py, Utils/Dataflow/test/pyDKB/json2TTL.py
Main changes:
* XXXProcessorStage classes are removed in favor of basic `ProcessorStage` + `set_(in|out)put_message_type()`;
* EOP marker is to be output in any processing mode (not only for stream output);
* default output directory changed from the "directory with input files" to `./out/`;
*(update)*
* `flush_buffer()` function clears the buffer after output.
=> [stack] pyDKB development (pt.4): Processor stage improvements.

Utils/Dataflow/pyDKB/dataflow/stage/ProcessorStage.py
Main changes:
* `__out_files()` method is splitted into a number of smaller methods:
* `get_ot_dir()`;
* `get_out_filename()`;
* `get_out_file_info()`;
* code was refactored for better readability;
* added some additional checks before using `hdfs.movefile()` for better handling of possible errors.
=> [stack] pyDKB development (pt.6): refactoring and minor improvement of ProcessorStage output files functionality.

Utils/Dataflow/016_task2es/task2es.py, Utils/Dataflow/054_docContent2TTL/docContent2TTL.py, Utils/Dataflow/091_datasetsRucio/datasets_processing.py, Utils/Dataflow/093_datasetsFormat/datasets_format.py, Utils/Dataflow/095_datasetInfoAMI/amiDatasets.py, Utils/Dataflow/pyDKB/dataflow/__init__.py, Utils/Dataflow/pyDKB/dataflow/communication/__init__.py, Utils/Dataflow/pyDKB/dataflow/communication/messages.py, Utils/Dataflow/pyDKB/dataflow/communication/stream/InputStream.py, Utils/Dataflow/pyDKB/dataflow/communication/stream/Stream.py, Utils/Dataflow/pyDKB/dataflow/communication/stream/__init__.py, Utils/Dataflow/pyDKB/dataflow/stage/ProcessorStage.py, Utils/Dataflow/pyDKB/dataflow/stage/__init__.py, Utils/Dataflow/skel/stage.py, Utils/Dataflow/test/pyDKB/json2TTL.py
Add `pyDKB.dataflow.communication` submodule to collect there all the functionality related to the data input/output:
* `pyDKB.dataflow.messages` is moved to this submodule;
* `stream` submodule added for implementation of message streams.
---
ToDo:
=> [stack] pyDKB development (pt.7): communication submodule

Utils/Dataflow/015_CDSDocuments/getCDSDocuments.py, Utils/Dataflow/016_task2es/task2es.py, Utils/Dataflow/018_PDFDownloader/getPDFfromCDS.py, Utils/Dataflow/030_PDFAnalyzer/flow.py, Utils/Dataflow/054_docContent2TTL/docContent2TTL.py, Utils/Dataflow/055_documents2TTL/documents2ttl.py, Utils/Dataflow/091_datasetsRucio/datasets_processing.py, Utils/Dataflow/093_datasetsFormat/datasets_format.py, Utils/Dataflow/095_datasetInfoAMI/amiDatasets.py, Utils/Dataflow/pyDKB/dataflow/communication/__init__.py, Utils/Dataflow/pyDKB/dataflow/communication/consumer/Consumer.py, Utils/Dataflow/pyDKB/dataflow/communication/consumer/FileConsumer.py, Utils/Dataflow/pyDKB/dataflow/communication/consumer/HDFSConsumer.py, Utils/Dataflow/pyDKB/dataflow/communication/consumer/StreamConsumer.py, Utils/Dataflow/pyDKB/dataflow/communication/consumer/__init__.py, Utils/Dataflow/pyDKB/dataflow/stage/ProcessorStage.py, Utils/Dataflow/skel/stage.py, Utils/Dataflow/test/pyDKB/json2TTL.py
All data taking fucntionality is moved from ProcessorStage to the
new submodule.
Accompanee changes:
* ProcessorStage has `configure()` method now: it parses arguments and
creates consumer to get input data from.
=> [stack] pyDKB development (pt.8): communication.consumer submodule.

Utils/Dataflow/pyDKB/dataflow/communication/stream/OutputStream.py, Utils/Dataflow/pyDKB/dataflow/communication/stream/__init__.py, Utils/Dataflow/pyDKB/dataflow/stage/ProcessorStage.py
All the functionaluity, related to the data output to a given file
descriptor, is gathered into the newly added class.
=> [stack] pyDKB development (pt.9): introduce OutputStream

Utils/Dataflow/pyDKB/dataflow/communication/__init__.py, Utils/Dataflow/pyDKB/dataflow/communication/consumer/Consumer.py, Utils/Dataflow/pyDKB/dataflow/communication/producer/FileProducer.py, Utils/Dataflow/pyDKB/dataflow/communication/producer/HDFSProducer.py, Utils/Dataflow/pyDKB/dataflow/communication/producer/Producer.py, Utils/Dataflow/pyDKB/dataflow/communication/producer/StreamProducer.py, Utils/Dataflow/pyDKB/dataflow/communication/producer/__init__.py, Utils/Dataflow/pyDKB/dataflow/communication/stream/InputStream.py, Utils/Dataflow/pyDKB/dataflow/communication/stream/OutputStream.py, Utils/Dataflow/pyDKB/dataflow/communication/stream/Stream.py, Utils/Dataflow/pyDKB/dataflow/communication/stream/__init__.py, Utils/Dataflow/pyDKB/dataflow/stage/ProcessorStage.py
All the functionality related to the output management (destination
choise, open/close files, etc.) is moved from ProcessorStage to the
`producer` submodule.
Minor improvements:
* output directory choiсe logic.
=> [stack] pyDKB development (pt.10): communication.producer submodule.

Utils/Dataflow/pyDKB/dataflow/communication/consumer/FileConsumer.py, Utils/Dataflow/pyDKB/dataflow/stage/AbstractStage.py, Utils/Dataflow/pyDKB/dataflow/stage/ProcessorStage.py
Changes:
* stage\`s `output_error()` method is improved to be more readable in the code and output;
* improved logging in `stop()` method (to output traceback for all the errors occured, not only the first one);
* additional log messages.
=> pyDKB: improve logging

Utils/Dataflow/pyDKB/dataflow/communication/consumer/FileConsumer.py, Utils/Dataflow/pyDKB/dataflow/communication/stream/InputStream.py
Refactoring:
* unused variable;
* some unifications;
* new metod for initialization of important `FileConsumer` property.
=> pyDKB refactoring

Utils/Dataflow/091_datasetsRucio/datasets_processing.py
Typo, tense concord, word usage...
=> DF/91: fix comments.

Utils/Dataflow/055_documents2TTL/documents2ttl.py
Discovered this problem while making tests for the stage.
=> Fix incorrect assignment of list elements

Utils/Dataflow/091_datasetsRucio/datasets_processing.py
Bug fixes:
* copy-and-paste typo (`-1` instead of `True`);
* uncaught exception from Rucio client.
=> Stage 091 fix

Utils/Dataflow/pyDKB/dataflow/dkbID.py
This function is used to retrieve something which is not None
and not an empty string. Fixed logic and description accordingly.
=> Fixed dataflow.firstValue().

Utils/Dataflow/pyDKB/common/json_utils.py
- Incrementing i1 advances the cycle (it is endless with i).
- Dot is removed when split() is made, so it is added back into
quoted keys.
=> Fixed quote-processing mechanism in nestedKeys().

Utils/Dataflow/README
Dataflow README file is actualized and (re)formatted.
=> DF readme update

Utils/Elasticsearch/requests/hashtag-steps-statistics-q.json, Utils/Elasticsearch/requests/hashtag-steps-statistics-r.json
NOTE: output sample is to be updated later, when data in ES are ready.
=> es/query: use "toths06" instead of "hs06*total_events".

Utils/Dataflow/pyDKB/dataflow/communication/consumer/FileConsumer.py, Utils/Dataflow/pyDKB/dataflow/communication/consumer/__init__.py, Utils/Dataflow/pyDKB/dataflow/communication/producer/__init__.py, Utils/Dataflow/pyDKB/dataflow/stage/ProcessorStage.py
Fix stage behaviour in file mode with no input files specified.
---
+ (pt.1) #202
=> pyDKB stage fix (pt.2)

Utils/Dataflow/pyDKB/dataflow/stage/ProcessorStage.py, Utils/Dataflow/test/pyDKB/case/03/cmd, Utils/Dataflow/test/pyDKB/case/03/err
Fix stage behaviour in case of no command line parameters passed.
---
+ (pt.2) #203
=> [pending] pyDKB stage fix (pt.3)

Utils/Dataflow/pyDKB/dataflow/stage/AbstractStage.py, Utils/Dataflow/pyDKB/dataflow/stage/ProcessorStage.py, Utils/Dataflow/test/pyDKB/case/01/err
Make pyDKB stage objects to log configuration.
---
+ (pt.3) #204
=> pyDKB stage fix (pt.4)

Utils/Dataflow/pyDKB/dataflow/communication/stream/InputStream.py, Utils/Dataflow/pyDKB/dataflow/communication/stream/Stream.py, Utils/Dataflow/pyDKB/dataflow/stage/ProcessorStage.py
pyDKB refactoring:
* unused method removed;
* list turned into iterator in InputStream class.
---
+ (pt.5) #206
=> pyDKB stage fix (pt.6)

Utils/Dataflow/test/pyDKB/README, Utils/Dataflow/test/pyDKB/case/19/after, Utils/Dataflow/test/pyDKB/case/19/before, Utils/Dataflow/test/pyDKB/case/19/cmd, Utils/Dataflow/test/pyDKB/case/19/err, Utils/Dataflow/test/pyDKB/case/19/info, Utils/Dataflow/test/pyDKB/case/19/out, Utils/Dataflow/test/pyDKB/case/20/after, Utils/Dataflow/test/pyDKB/case/20/before, Utils/Dataflow/test/pyDKB/case/20/cmd, Utils/Dataflow/test/pyDKB/case/20/err, Utils/Dataflow/test/pyDKB/case/20/info, Utils/Dataflow/test/pyDKB/case/21/after, Utils/Dataflow/test/pyDKB/case/21/before, Utils/Dataflow/test/pyDKB/case/21/cmd, Utils/Dataflow/test/pyDKB/case/21/err, Utils/Dataflow/test/pyDKB/case/21/info, Utils/Dataflow/test/pyDKB/test.sh
Add test cases for file output.
---
+ (pt.10) #212
=> pyDKB stage fix (pt.11)

Utils/API/server/lib/dkb/api/__init__.py, Utils/API/server/lib/dkb/api/exceptions.py, Utils/API/server/lib/dkb/api/handlers.py, Utils/API/server/lib/dkb/api/methods.py
Basic functionality of category/method handling is implemented:
* add method (bind method with handler function): `methods.add()`;
* get category "content" by path (methods and subcategories;
* list category "content";
* get method handler (by path).
=> API: `info` and `server_info` methods.

Utils/API/server/cgi-bin/dkb.fcgi
Fixed:
* server failure in case of "unknown" status code (not properly defined);
* query string multi-valued parameters parsing.
=> API: bug fixes

Utils/API/server/cgi-bin/dkb.fcgi, Utils/API/server/lib/dkb/api/__init__.py, Utils/API/server/lib/dkb/api/handlers.py, Utils/API/server/lib/dkb/api/methods.py, Utils/API/server/lib/dkb/api/storages/es.py
Minor improvements:
* all `* Merge` steps are joined into a single (unless `detailed` parameter specified);
* legend items order corresponds the real steps order;
* method accepts start/end interval boundaries;
* adjusted number of bins in the histogram (automatic and manual).
New parameters:
* `bins`;
* `start`;
* `end`;
* `bins`.
=> API: /task/hist method improvements

Utils/API/server/lib/dkb/api/__init__.py, Utils/API/server/lib/dkb/api/handlers.py
Bug fix:
* `IndexError` in case of a short time interval due to the number of different steps less then the number of steps in the "ordered" list.
Improvemets:
* image title (hashtags);
* axis labels;
* larger fonts.
=> API: /task/hist improvements

Utils/Dataflow/pyDKB/dataflow/communication/consumer/FileConsumer.py, Utils/Dataflow/pyDKB/dataflow/stage/AbstractStage.py
This PR replaces frozen #172, and also covers the comment in #221 concerning the help message.
Changes:
* unused class variable removed;
* sources initialization is moved to a separate method (FileConsumer);
* help message correction.
=> pyDKB: minor improvements

Utils/Dataflow/run/data4es-start
Minor fixes:
* removed obsolete piece of code;
* typo fixed (log message);
* ensure all error messages go to STDERR;
* fix typo in variable name (fortunately, it didn\`t affect anything).
Improvements:
* add `log()` function to unify logging;
* add process start/end log messages with (overall) timing.
=> DF/data4es: fixes and minor improvements.

Utils/API/server/lib/dkb/api/__init__.py, Utils/API/server/lib/dkb/api/storages/es.py, Utils/API/server/lib/dkb/api/storages/es/query/task-steps-hist
Improved `task_hist` request handling:
* fix issue with undefined task `start_time`;
* improve undefined `end_time` handling.
=> API/task_hist: fix handling of tasks with undefined start/end time

Utils/Dataflow/pyDKB/common/hdfs.py, Utils/Dataflow/pyDKB/dataflow/communication/producer/HDFSProducer.py
Fix some HDFSProducer-related errors discovered during tests.
=> PyDKB hdfs fix

Utils/Dataflow/pyDKB/dataflow/stage/ProcessorStage.py
=> pyDKB: typo fix (docstrings).

Utils/Dataflow/pyDKB/dataflow/stage/ProcessorStage.py, Utils/Dataflow/test/pyDKB/case/20/err, Utils/Dataflow/test/pyDKB/case/21/err
Previous version of the description gave no clue to "what is this function used for"; fixed now.
=> pyDKB: improve docs

.travis.yml, Tests/travis/README_long_lines.sh, Tests/travis/README_tabs.sh, Tests/travis/README_trailing_spaces.sh, Tests/travis/functions.sh, Tests/travis/tests/test_funtions_getURL.sh
To check changes in README files by travis-ci added set of scripts to Tests/travis and updated travis configuration.
All checks goes in own check phase.
Fixes: #268
=> Travis checks for README files

Utils/Dataflow/025_chicagoES/stage.py
Update descriptions of available argument values in two functions to match the code.
=> 025 description fix

Utils/Dataflow/017_adjustMetadata/adjustMetadata.py
- Remove dictionary redifinition.
- Replace a succession of IFs with a cycle.
=> 017 get_category() improvement

Utils/Elasticsearch/mapping/README, Utils/Elasticsearch/mapping/tasks.mapping
ES scheme update, intended to bring some order to the existing structure without significant changes affecting the `data4es` process.
What is changed:
* formatting;
* fields types added with copy-and-paste (or simply without too careful consideration).
=> ES scheme update

Utils/API/server/dkb.yaml.example, Utils/API/server/es_params.example, Utils/API/server/lib/dkb/api/config.py, Utils/API/server/lib/dkb/api/storages/es.py, Utils/API/server/setup.sh
Decided to have single configuration file for the REST API server application, in YAML format.
=> API: app configuration file

Utils/API/server/lib/dkb/api/__init__.py
=> API: update version info (0.2.dev20191017).

Utils/API/server/setup.sh
In previous version if WWW dir was changed by cmdline parameter
`--dest`, in config directory default path still was used original
(default) value of `$WWW_DIR`, so if `--dest` is used `--cfg-dir` must
be used as well.
Now value of `$CFG_DIR` (default or passed via `--cfg-dir`) is treated
as-is if it is an absolute path (starts with "/" or, in case of
`--cfg-dir`, with "." to point to a file in a local (sub)directory);
else it is considered as a subdirectory of `$WWW_DIR` (whatever value it
has).
=> API/setup: cfg dir treatment improvement

Utils/API/server/cgi-bin/dkb.fcgi
If local `conf/dkb.yaml` exists, it will be copied to the WWW app
directory. It simplifies usage of `$WWW_DIR/conf` as `$CFG_DIR` (which
is a default value).
=> API/setup: add `conf/dkb.yaml` to setup files list.

Utils/API/server/lib/dkb/api/__init__.py, Utils/API/server/lib/dkb/api/storages/es.py
We need to use only `task` documents, not all documents in the index.
=> API: kwsearch fix

Utils/API/server/setup.sh
Fix issues preventing regular user from installation of own development instanse of API server.
ToDo:
=> API: setup fix

Utils/Dataflow/run/data4es-consistency-check
Changes:
* check results to be output to STDOUT;
* debug mode introduced (in which transitional data between stages are written to local files);
* "process finished"-like log message added.
=> DF/data4es-consistency-check: improve start script

Utils/API/server/lib/dkb/api/__init__.py, Utils/API/server/lib/dkb/api/storages/es.py
Changes:
* from data format-based statistics excluded formats: `"DAOD"`, `"DRAW"`;
* codestyle improvement (quotes unification).
=> API: 0.2.dev20200305 (exclude raw data formats)

Utils/Dataflow/009_oracleConnector/query/prodsys2ES.sql
Update the query's comment describing tables used in it.
=> 009 query comment update

Utils/Dataflow/README
1. Add introductory section with some general info about what's in the directory.
2. Update sub-headers design (originally they were not unified, and the one of presented designs I decided to follow appeared to be too heavy).
=> DF: readme update

Utils/Dataflow/095_datasetInfoAMI/amiDatasets.py
Part of the series of pull requests intended to replace #282.
Implement changes that affect and improve the stage logic, but aren't directly related to AMI team's feedback.
=> 095 update, part 1.2: logic

Utils/Dataflow/skel/stage.py
Usage of 'traceback' and exceptions handling is no lonnger needed since it is taken care of in the pyDKB library.
=> DF/skel: update stage example.

.github/workflows/doc_update_on_push2master.yml
After every push to master this workflow will create PR for
documentation update.
Fixes part 3 of #383
=> Use github action for automatically generate documentation

Utils/Elasticsearch/mapping/README, Utils/Elasticsearch/mapping/tasks-nested.mapping
Replace parent/child relationship in ES mapping with nested fields.
ToDo *(in another PR)*:
=> DKB/nested. Pt.1: ES mapping update.

Utils/Dataflow/data4es-nested/091_datasetsRucio/datasets_processing.py
* Join functions `process_{in|out}put_ds` in `process_ds`.
* Make `process_*` operate with `dict` objects instead of `JSONMessage`s
*(it is more natural and readable, for \*Message objects are supposed to serve data input/output tasks, not processing)*.
=> DF/data4es-nested/091: refactoring.

Utils/Elasticsearch/mapping/tasks-nested.mapping
Fields added:
* `cloud`;
* `site`.
=> ES/mapping/nested: add missed fields.

Utils/Dataflow/data4es-nested/run/data4es-consistency-check, Utils/Dataflow/data4es-nested/run/data4es-start, Utils/Dataflow/data4es/run/data4es-consistency-check, Utils/Dataflow/data4es/run/data4es-start, Utils/Dataflow/shell_lib/run_stage
`run_stage` is a shell function taking care of stage command execution. It does the following:
* checks if stage command is defined (by stage ID);
* runs stage command;
* in debug mode: saves all stages' input and output in local files.
=> DF/data4es(-nested): run stage

Utils/API/server/lib/dkb/api/__init__.py, Utils/API/server/lib/dkb/api/methods.py, Utils/API/server/lib/dkb/api/misc.py, Utils/API/server/lib/dkb/api/storages/__init__.py
Changes:
* get rid of mirroring all the API methods in the `lib/dkb/api/storages/__init__.py`;
* simplify method's handler lookup.
=> API: code refactoring.

Utils/API/server/lib/dkb/api/__init__.py, Utils/API/server/lib/dkb/api/handlers.py, Utils/API/server/lib/dkb/api/methods.py, Utils/API/server/lib/dkb/api/misc.py
Changes:
* (UI) '/info' method is now available for all catigories;
* (code) method handlers can be linked to "wildcard" (regex) paths.
=> API: wildcard handler

Utils/API/server/lib/dkb/api/__init__.py, Utils/API/server/lib/dkb/api/storages/es/transform.py
=> API: typo fix.

Utils/API/server/cgi-bin/dkb.fcgi, Utils/API/server/lib/dkb/api/__init__.py, Utils/API/server/lib/dkb/api/handlers.py, Utils/API/server/lib/dkb/api/methods.py, Utils/API/server/lib/dkb/api/storages/es/methods.py, Utils/API/server/lib/dkb/api/storages/es/transform.py
Minor change:
* code architecture reworked: request execution metadata are now separated from requested method's results.
=> API: request metadata handling rework.

Utils/Dataflow/data4es-nested/091_datasetsRucio/datasets_processing.py
Default behaviour: pass message as is, marking it 'incomplete'.
New behaviour: replace field `output` (list of output datasets) with `output_datasets` (list of nested documents representing datasets).
=> DF/data4es-nested/091: fix 'skip' scenario behaviour.

Utils/API/server/lib/dkb/api/__init__.py, Utils/API/server/lib/dkb/api/storages/__init__.py
Minor changes:
* bug fix (typo in metadata field's name).
=> API: bug fix

Utils/API/server/lib/dkb/api/__init__.py, Utils/API/server/lib/dkb/api/storages/es/methods.py, Utils/API/server/lib/dkb/api/storages/es_nested/methods.py
Fix issue with wildcard keyword search.
Issue details: "local variable 'tokens' referenced before assignment".
=> API: bug fix (wildcard keyword search).

Utils/API/server/cgi-bin/dkb.fcgi, Utils/API/server/lib/dkb/api/__init__.py, Utils/API/server/lib/dkb/api/handlers.py
Changes:
* fix /task/hist right border parameter name in method description;
* fix expected datetime parameters value format.
=> API: bug fix (/task/hist 'end' parameter).

Utils/API/server/lib/dkb/api/__init__.py, Utils/API/server/lib/dkb/api/storages/es/common.py, Utils/API/server/lib/dkb/api/storages/es_nested/common.py
Changes:
* set default ES request timeout to 10 min.
=> API: default ES timeout

Utils/Elasticsearch/tools/load_mapping.sh
=> refactor(ES): improve readability (tools/load_mapping.sh)

Utils/Dataflow/data4es/071_esConsistency/consistency.py
=> refact(DF/071): make ES connect string generation more DRY

Utils/Dataflow/data4es/069_upload2es/load_data.sh, Utils/Dataflow/data4es/071_esConsistency/consistency.py, Utils/Elasticsearch/config/es.example, Utils/Elasticsearch/tools/load_mapping.sh, Utils/Elasticsearch/tools/search.sh
=> [pending] DF/069: explicit `Content-Type` header

Utils/Dataflow/data4es/095_datasetInfoAMI/amiDatasets.py
=> Refs: #449: data4es | 095_datasetInfoAMI | add mc23 for Atlas AMI SCOPE
