PanDAWMS/dkb

Utils/Dataflow/pyDKB/dataflow/dkbID.conf

Configured pyDKB to use following values for Document dkbID generation (listed in order of priority):
* CDS:
* report_number['internal']
* report_number['report_number']
* report_number
* GLANCE:
* ref_code
* id

pyDKB configuration

---

Utils/Dataflow/pyDKB/common/__init__.py
Utils/Dataflow/pyDKB/common/exceptions.py
Utils/Dataflow/pyDKB/common/hdfs.py
Utils/Dataflow/pyDKB/dataflow/stage/AbstractProcessorStage.py

Add possibility to specify only the directory without listing all the files.
Now if --input-dir is specified but no input FILE presented, the Stage will try to get list of files in the directory and use them as input.
If the directory does not exist, error message appears.
If the directory is empty, nothing happens.

pyDKB: --input-dir parameter enhancing

---

Utils/Dataflow/pyDKB/common/hdfs.py
Utils/Dataflow/pyDKB/dataflow/messages.py
Utils/Dataflow/pyDKB/dataflow/stage/AbstractProcessorStage.py
Utils/Dataflow/pyDKB/dataflow/stage/processors.py
Utils/Dataflow/pyDKB/dataflow/types.py
Utils/Dataflow/test/pyDKB/README
Utils/Dataflow/test/pyDKB/input
Utils/Dataflow/test/pyDKB/json2TTL.py

The implementation of output logic according to the command line parameters was implemented.
**Major changes**
1. AbstractProcessorStage.process() method changed:
- has became a static method with two parameters: `stage, message`
...to allow usage of the Processor Stage output() method from within the process() implementation
- must return True or False
...to indicate if the processing was successful or not. If the
processing has failed, all the output messages are dropped
2. AbstractProcessorStage.stop() method added
- must be called after run() to finalize internal processes
3. Test stage `Dataflow/test/pyDKB` added
- to demonstrate how to use Processor Stage and test its functionality
**The logic**
Output messages are buffered in `__output_buffer` parameter, and pushed forward only …

pyDKB: Processor Stage output full implementation

---

Utils/Dataflow/015_CDSDocuments/getCDSDocuments.py

1. Bug fix:
`form_output_data()` would generate list of supporting notes with same CDS data for every note in the list. It was due to the usage of the same dict variable for every note (not reinitialized every time). As the dict is a mutable object (and the variable -- is a reference to the object), when the object is rewritten, it is rewritten for every occurance of it in the output list.
1. Codestyle fix:
* PEP-8 styling
* unified quotation marks
The rule is to use **single** quotation mark for **identifiers** and **single characters** (except specials), and **double** quotation mark -- for **string values**, **docstrings** etc.

Stage 015 cds documents fix

---

Utils/Dataflow/015_CDSDocuments/getCDSDocuments.py

Collection can look like:
` {"primary": "ATLAS", ...} `
or
` [ {"primary": "ATLAS", ...}, ... ] `
(...and maybe some other way...)
Previous type checks acted like it always was a list and lead to
uncaught exceptions if it wasn`t.
Now it (hopefully) can handle whatever comes.

DF/15: bug fix (collection verification checks)

---

Installation/OrientDB/install.sh
Tests/Dockerfile.OrientDB_install
Tests/docker.sh

Installation script tested on:
* Ubuntu 14.04 
* CentOS 6.5
NOTE:
Without `-DskipTests` Java project building fails on LuceneRangeTest, but the installation seems to work.
So for the time being I think it`s Ok.

Installation: add OrientDB installation script.

---

Utils/Dataflow/018_PDFDownloader/getPDFfromCDS.py
Utils/Dataflow/018_PDFDownloader/kerberos_init.sh
Utils/Dataflow/018_PDFDownloader/switch_realm
Utils/Dataflow/018_PDFDownloader/transferPDF.sh

Main changes:
* stage learned how to remove temporary files after itself;
* switch_realm moved to a separate file (as it is useful not only for this stage);
* stage dies on failure after 3 retries;
Minor fixes:
* wrong varname;
* PDF document choise by version;
* relative filename issue;
* wrong log message format;
* STDERR and STDOUT in `transferPDF.sh`
* more precise username definition in `kerberos_init.sh`

Stage 018: PDFDownloader

---

Utils/Dataflow/000_kafka/ru/kiae/dkb/kafka/streams/processor/external/ExternalProcessorSupplier.java

As without understanding, what process belongs to what thread, we can analyze the timing only "as is", but can`t reconstruct the full chain of timings for a single record from the initial source.

DF/kafka: modify Streams timing to log Thread name as well.

---

Utils/Dataflow/030_PDFAnalyzer/manager.py

Small update with changes serving for:
- Catching up with dataflow-with-document-content -> master migration.
- ~~Creating a base for extension development.~~ (Removed per conversation below.)

Stage 030 update

---

.travis.yml
Utils/Dataflow/009_oracleConnector/DButils.py
Utils/Dataflow/009_oracleConnector/Oracle2JSON.py
Utils/Dataflow/pyDKB/dataflow/cds.py

Change PEP8 codestyle checks.
Since now the only ignored by `pep8` (https://pypi.python.org/pypi/pep8) codes are:
* W503 (line break before binary operator):
https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator
* W292 (no newline in the end of file):
as we work in different OSs, it might be a problem
If there are any other codes that you think must be ignored, please write it in the comments..

Travis: update codestyle checks

---

Utils/Dataflow/009_oracleConnector/query/prodsys2ES.sql

The issue is that LEFT JOIN doesn't return all records
from the left table.
The solution is to change WHERE clause to AND
so that the condition is part of the join condition, not a filter applied after the join.
Now all rows in the left table will be present in the result.

SQL: LEFT JOIN error fixed

---

Utils/Dataflow/pyDKB/common/__init__.py
Utils/Dataflow/pyDKB/common/custom_readline.py
Utils/Dataflow/pyDKB/dataflow/stage/AbstractProcessorStage.py
Utils/Dataflow/pyDKB/dataflow/stage/AbstractStage.py

pyDKB: EOM/EOP markers

---

.travis.yml
Utils/DataFromAMI/getDataPeriods_AMI.py
Utils/DataFromAMI/getRunNumbersFromAMI.py
Utils/Dataflow/030_PDFAnalyzer/manager.py
Utils/Dataflow/030_PDFAnalyzer/pdfwork.py
Utils/Dataflow/030_PDFAnalyzer/xmltable.py
Utils/Dataflow/091_datasetsRucio/datasets_processing.py
Utils/Dataflow/skel/stage.py

As `pep8` is obsolete, we may switch to the recomended `pycodestyle`.
However `pycodestyle` is a bit more strict about some things (see the Travis checks for this PR).
Particularly, it suggests to:
* E741: avoid ambiguous variable names (like 'l', 'O', 'I');
* E722: avoid "bare except".
The first, I think, need no additional explaination. It is just a question of "shell we pretend there`s no ambiguity" or fix it now.
For the second I would refer to the PEP-8 itself:
A bare "except:" clause will catch SystemExit and KeyboardInterrupt exceptions,
making it harder to interrupt a program with Control-C, and can disguise other problems.
If you want to catch all exceptions that signal program errors, use "except Exception:"
(bare except is equivalent to "except BaseException:").
A good rule of …

Travis: pep8 checks update

---

Utils/Dataflow/030_PDFAnalyzer/manager.py
Utils/Dataflow/030_PDFAnalyzer/xmltable.py
Utils/Dataflow/093_datasetsFormat/datasets_format.py

ToDo:
---
As far as I understand, this warning appears when backslash is used in
an ordinary string as an ordinary character.
It makes sense -- as one might not remember all the escape sequences
exist (like `'\n'`, `'\\'`, `'\xYY'`, etc.), and can unintentionly put
it into an ordinary string (say, `'\def'` is an ordinary string of 4
characters, while `'\abc'` icontains 3 characters, first of which is
ASCII Bell (BEL) symbol).
Thus it is suggested to use `'\\'` in an ordinary string, when sole
backslash is needed, or use raw strings (like this: `r'\abc'`).
Note: `re.compile()` accepts standard Python escape sequences, like
`'\n'` (so `r'\n'` is treated same way as pure `'\n'`).

Codestyle: fix W605 (invalid escape sequence).

---

Utils/Dataflow/pyDKB/dataflow/stage/AbstractStage.py

It used to output with `logLevel.X` first and last N lines:
* ERROR: 3 lines
* DEBUG: 8 lines (but the 3 with ERROR level)
* TRACE: all the others
Now it outputs with `logLevel.X` only the last N lines:
* ERROR: 1 line
* DEBUG: all the others
I believe that the last line gives the most important information to
understand the content of the error; whole traceback (including first
lines) is required only for debug.
TRACE level is more to understand how things are going during the
program execution to locate unexpected behaviour, not to "get more
detais about the error".

[stack] pyDKB development (pt.5): improve output_error() method of AbstractProcessor.

---

Utils/Dataflow/069_upload2es/load_data.sh
Utils/Dataflow/run/data4es-start

Sometimes we need to run two or more `data4es` processes with different
configurations (say, regular updates every hour, reverse update for data
repair, weekly update to get updated data from original sources, where
timestamp was not updated properly). To make it possible, we need to at
least be able to set "where to read configuration from" without changing
code.

DF: data4es config lookup

---

Utils/Dataflow/run/data4es-start
Utils/Dataflow/run/data4es-status
Utils/Dataflow/run/data4es-stop

To have possibility to run two or more different processes for `data4es`
dataflow process, we need to separate their home directories (where the
process stores temp files, including pidfile).
---
~~Waiting for: #137~~

data4es: individual home directory for a process.

---

Utils/Dataflow/019_esFormat/run.sh
Utils/Dataflow/run/data4es-start

Stage 19, used in `data4es` process, never took config file firom command line and thus for any `data4es` process all ES settings were the same.

data4es: fix config file usage (stage 19)

---

Utils/Dataflow/pyDKB/dataflow/communication/stream/Stream.py
Utils/Dataflow/pyDKB/dataflow/communication/stream/__init__.py
Utils/Dataflow/pyDKB/dataflow/communication/stream/exceptions.py

Derfinition for StreamException is moved to a separate file, as it must
be imported in `stream` submodules, but was defined after the submodules
are imported in `__init__`.

pyDKB/*/stream: bug fix (StreamException not defined).

---

Utils/Dataflow/pyDKB/dataflow/communication/consumer/Consumer.py
Utils/Dataflow/pyDKB/dataflow/communication/consumer/FileConsumer.py

When only directory with input files is specified, it is better to work
only with files with proper extension (detected by input message type).
It allows to put output files to the same directory, or even work in the
same directory with the executable.
---
~Waits for: #149~ *(merged)*

pyDKB/*/consumer: make FileConsumer to check input file extension.

---

Utils/Dataflow/pyDKB/dataflow/communication/consumer/FileConsumer.py
Utils/Dataflow/pyDKB/dataflow/communication/stream/InputStream.py

This reverts commit f4b04cc481a504859fd7468dcc6326fa0f821766, reversing
changes made (by branch 'pyDKB-refactoring') to
d5259c0252d2876b0e57804a7de230237acc46f9 (branch 'pyDKB').
The revert is required as PR #149 introduced a bug, due to which any
stage program failed on start at least in `stream` mode:
```
Utils/Dataflow/test/pyDKB$ ./json2TTL.py -m s
(WARN) pyDKB.dataflow.cds failed (No module named
invenio_client.contrib)
Traceback (most recent call last):
File "./json2TTL.py", line 75, in <module>
main(sys.argv[1:])
File "./json2TTL.py", line 56, in main
stage.configure(args)
File "./../../pyDKB/dataflow/stage/ProcessorStage.py", line 178, in
configure
.setType(self.__input_message_type) \
File "./../../pyDKB/dataflow/communication/consumer/__init__.py", line
62, in build
instance = …
```

Revert PR #149

---

Utils/Dataflow/pyDKB/dataflow/communication/messages.py
Utils/Dataflow/pyDKB/dataflow/stage/ProcessorStage.py

Fix docstring in `dataflow.communication.messages`.
[WIP] is to leave it as PR for a while, before we start to bring order to the whole `pyDKB` documentation.

docs/pyDKB: fix docstrings

---

Utils/Dataflow/019_esFormat/esFormat.php
Utils/Dataflow/019_esFormat/run.sh
Utils/Dataflow/run/data4es-start

Suddenly realized that processing stage 019_esFormat does not follow the EOM/EOP marker paradigm.
For now it is OK, but when we switch to Kafka-supervised version of the dataflow, it will be embarassing to find out the stage does not support basic communication protocol.
ToDo:

Stage 019: markers

---

Utils/Dataflow/.gitignore
Utils/Dataflow/pyDKB-setup.py
Utils/Dataflow/pyDKB/VERSION
Utils/Dataflow/pyDKB/__init__.py

Add simple setup script to avoid dancing around `sys.path`.
To install the `pyDKB` library for the development, run `./pyDKB-setup.py develop`.
It will fake-install library, creating link to the directory with source
files, and there will be no need to re-install library after every
change.
To install `pyDKB` "for usage", use `./pyDKB-setup.py install`.
ToDo:

pyDKB setup script

---

Utils/Elasticsearch/requests/hashtag-steps-statistics-q.json
Utils/Elasticsearch/requests/hashtag-steps-statistics-r.json

Currently query returns:
* total size of input datasets;
* total number of requested events;
* total size of output datasets;
* total number of events in output datasets;
* number of tasks by task status.
for:
* tasks with given hashtag;
* with all statuses but:
* aborted;
* failed;
* broken;
* obsolete;
* aggregated by step;
* for not deleted output datasets.
The example response is given for "gammajets" hashtag.

es/query: add query to get statistics by task steps for hashtag.

---

Utils/Elasticsearch/requests/deriv-ratio-q.json
Utils/Elasticsearch/requests/deriv-ratio-r.json

Suggested query returns total input / output dataset size and events number for tasks by parameters:
* project name;
* current AMI tag of the task;
* output dataset data format.
First it selects all documents of type 'task':
* status: 'done',
* primary_input: 'aod' (dataset name contains this term),
* project: parametric value,
* AMI tag: parametric value
...with following conditions:
* primary_input dataset size > 0,
* among output datasets there is a dataset with data in required format (parametric value), and its size is > 0.
Then found documents are aggregated:
* total input datasets size (sum),
* total input events sumber (sum),
* total output datasets size and events number for:
* not deleted datasets
* with data in given format.

ES query for prodtask-dev DKB web-interface

---

Utils/Elasticsearch/requests/hashtag-steps-statistics-q.json
Utils/Elasticsearch/requests/hashtag-steps-statistics-r.json

Sometimes there may  appear tasks with `start_time` > `end_time`, so to
get correct value this possibility should be taken into account.

es/query: fix negative walltime in hashtag-steps stats.

---

Utils/Dataflow/009_oracleConnector/Oracle2JSON.py

Initially it was decided that if a parameter is specified in the config
file, then it should not be treated as "not specified" even if it has
empty value, and left with empty string value.
However I made same mistakes multiple times already, leaving the
parameter when I meant "not specified", like:
```
[timestamps]
initial =
final = 01-03-2014 00:00:00
...
```
So I decided that if we are aware about the default values for a
parameter, than it should not be expected to have "empty string" value
whenever it is used.
If one day we shall need the empty string, it will be solved in its
turn.

DF/09: fix issue with empty start/end time config values.

---

Utils/Dataflow/009_oracleConnector/Oracle2JSON.py
Utils/Dataflow/009_oracleConnector/README
Utils/Dataflow/config/009.cfg.example
Utils/Dataflow/run/data4es-start

Two main changes:
* added logging of the stage configuration at startup;
* 'mode' (SQUASH|PLAIN) parameter was moved from command line to the config file.
Now the startup log looks like this:
```
$ ./Oracle2JSON.py --config ./config 
(INFO) Config: parameter 'initial' (section 'timestamps') is not configured. Using default value: 2019-01-23 12:13:32.585796
(INFO) Stage 009 configuration (/home/dkb/dkb-dev.git/Utils/Dataflow/009_oracleConnector/./config):
(INFO) ---
(INFO)  step_seconds : '-3600'
(INFO)  initial_date : '2019-01-23 12:13:32.585796'
(INFO)  offset_file  : '/home/dkb/dkb-dev.git/Utils/Dataflow/009_oracleConnector/.offset'
(INFO)  mode         : 'SQUASH'
(INFO)  queries      : '{'tasks': {'params': {'production_or_analysis_cond': '>'}, 'file': …
```

Stage 009 update

---

Utils/Dataflow/009_oracleConnector/README

Currently there are two examples of the config file for the stage - the one in `Utils/Dataflow/config/` is more up to date, so the one in stage 009's readme is replaced with a link to the former.
Noticeable difference between the two examples is the description of the change introduced in bef4178 -
`Utils/Dataflow/config/009.cfg.example` was updated, but 009's readme was not. Because of this, using the readme's config for launching the stage would lead to failure due to missing query parametric values.

Stage 009 config example's duplicate.

---

Utils/Dataflow/009_oracleConnector/README
Utils/Dataflow/config/009.cfg.example

The parameter was removed in PR #193 (b97dc7a), but not all the docs
were updated there.
Config file example is updates to keep information about the fact that
'PLAIN' mode currently works only with 'tasks' query.

DF/009: fix README (remove obsolete cmdline '--mode' explaination).

---

Utils/Dataflow/009_oracleConnector/dbConnection.py
Utils/Dataflow/config/009.cfg.example

Problems with error handling:
- A single missing parameter leads to KeyError. Add interception for it
to display a message that points to the configuration.
- The whole configuration missing leads to (even more puzzling)
ORA-00911. Add a warning when no parameters were configured that also
points towards configuration. Since it is possible to use a query
without parameters, no warning should be displayed in such case. Add
a check to only display the warning when the query contains single '%'
(double percent '%%' means that '%' was escaped, so it's allowed).
Also, a file is opened but not closed in the function - fixed that.

Stage 009: Improve query saving procedure.

---

Utils/Dataflow/test/pyDKB/test.sh

Improve test utility: make it save failure details in its working directory: `$CASE_ID_{err|out}.diff` for diff results and `$CASE_ID.{err|out}` for real output of the case.
---
+ (pt.14) #216

pyDKB stage fix (pt.15)

---

Utils/Dataflow/test/pyDKB/README
Utils/Dataflow/test/pyDKB/test.sh

Test utility improvements:
* `--list` -> `--list [TYPE]` (allows to output specific type of test case information: `todo`, `cmd`, ...);
* `--todo` removed (as it is replaced with `--list todo`);
* `--no-info` (allows to skip test cases description and output only information of specific `TYPE`).
---
+ (pt.16) #218

pyDKB stage fix (pt.17)

---

Utils/API/server/nginx.dkb.conf

Usually Nginx has the pre-defined list of fcgi parameters, and we have
no reason to avoid it in favor of our own list (that can be shorter, but
we will always have something forgotten...)

API/setup: improve Nginx config file for DKB API sever.

---

Utils/API/server/lib/dkb/api/__init__.py
Utils/API/server/lib/dkb/api/handlers.py
Utils/API/server/lib/dkb/api/storages/__init__.py
Utils/API/server/lib/dkb/api/storages/es.py
Utils/API/server/lib/dkb/api/storages/exceptions.py

New API method (`/task/chain?tid=...`) is added.
The method returns chain info in the following format:
```
{
...,
tidN: [childN_1, childN_2, ...],
...
}
```
To be used in chain-representing interfaces like [the one in BigPanDA](https://bigpanda.cern.ch/ganttTaskChain/?jeditaskid=7999893).

API: /task/chain method

---

Utils/API/server/lib/dkb/api/storages/es.py

If there is record for a given task, just no `chain_id`, we should not raise
`NoDataFound` -- it looks like there's no information for the task at all.

API: /task/chain method fix

---

Utils/Dataflow/test/pyDKB/test.sh

Add `-a` parameter to `grep` command to avoid "Binary file matches." in
the output (instead of the expected lines of STDERR).
---
* pt.21 (#223)

pyDKB stage fix (pt.22)

---

Utils/Dataflow/009_oracleConnector/Oracle2JSON.py
Utils/Dataflow/config/009.cfg.example

Previously 'naive' datetime objects were used, meaning in fact that we
treat `timestamp` field as timestamp in the local time zone. It has some
effect only when `now()` is used as a right limit of the integration
interval.
It is said (by M.Borodin) that `timestamp` is supposed to be in UTC, but
in fact it can be UTC or CET or CEST depending on when and who writes
the data.
Setting timestamp time zone to local time zone meant that records,
written with proper UTC, are likely to be missed (as we check every interval
one or two hours earlier then records are written).
Setting timestamp time zone to the UTC means that for records with
timestamp in CE(S)T we won't see changes as soon as they are written to
the Oracle DB; but they will be handled later. It is not best, but still
better than …

DF/09: add possibility to specify timestamps time zone (set to UTC).

---

Utils/Dataflow/009_oracleConnector/Oracle2JSON.py

There was used not very readable way to get current datetime in specific
timezone; new way looks much simplier and gives same result.
Also, it helps in case of undefined `OFFSET_TZ`: if it is `None` and no
`tz` is passed to the function, we will end up with `None.fromutc(...)`,
which will result in `AttributeError`. In the new version same situation
leads simply to `datetime.now(None)`, which is interpreted as "No time
zone specified, so use local time zone." Looks reasonable enough.

DF/009: improve `offset_now()` function.

---

Utils/Dataflow/pyDKB/dataflow/stage/AbstractStage.py

We tend to write docstrings as "Do X", not "Does X" (according to
PEP-257). This method's docstring was inconsistent with the rule, so
fixed now.

pyDKB: minor fix (docstring)

---

Utils/Dataflow/009_oracleConnector/Oracle2JSON.py
Utils/Dataflow/config/009.cfg.example

Add an option to get data in stage 009 with the final date set to relative 'N seconds/minutes/hours/... ago' - it is already possible, but only with N = 0. One of the goals of this change is to be able to have a delay between data loading and data consistency checking, to avoid discrepancies caused by constant updates of data in Oracle which are mirrored to ES only when another data loading is performed.

Stage 009: delay

---

Utils/Dataflow/019_esFormat/README
Utils/Dataflow/019_esFormat/esFormat.php
Utils/Dataflow/run/data4es-start

* fix input stream handling (no EOM was taken into account for the input stream);
* more strict output message definition (it must include last `\n` symbol as it is required by ES bulk API and must get there -- and if it is added as EOM, it will be removed on the next stage);
* new default EOM value (as `\n` appears in the message body, it can not be used as EOM);
* README updated accordingly.

DF/019: EOM handling improvement

---

Utils/Dataflow/091_datasetsRucio/datasets_processing.py

Fortunately, we didn't have dataset names like `scope:name` in the
stage input. At all ;)

DF/091: fix copy-and-paste typo in code.

---

Tests/travis/README_long_lines.sh

`echo "" | wc -l` returns 1. Real thing that this check do is checking
that something passes long lines filter.
We should check exactly this, not lines count or anything else.

travis-readme (fix): fixed check that long lines was found

---

Utils/Dataflow/025_chicagoES/stage.py

Aggregation queries often fail due to the `ConnectionTimeout`.
This PR is to fix the situation; it also adds extra logging for failed queries, so that one could check things more carefully if needed.

DF/25: request timeout

---

Utils/Dataflow/README

This update is about the description of stage types.
The main reason to add this block is a declaration what stage in a dataflow
pipeline is responsible for data preparation before uploading (sink or
transform stage).
We consider to leave sink stages pretty simple. All data preparation
work should be done by pre-sink stage -- the last one transform stage in
any data pipeline.

DF: update README

---

Utils/API/server/setup.sh

Now it will be enough to run `setup.sh` once with all configuration parameters required (`--dest`, etc). They will be stored in user home directory in file `~/.dkb-api` and reused on the next run (and still can be modified with cmdline parameters).
New command line parameters:
* `--restore-defaults` -- remove stored configuration;
* `--restore-cfg` -- restore previous configuration;
* `--show-cfg` -- show current configuration.

API/setup: keep installation parameters

---

Utils/Dataflow/060_upload2virtuoso/input
Utils/Elasticsearch/tools/load_data.sh

Stage 053 was removed long ago; an example of TTL files can be found in
output of stage 054.
ES-related tool (Utils/Elasticsearch/tools/load_data.sh) was turned into
stage 060, but somehow the link was set incorrectly.

Fix broken symlinks.

---

Utils/Dataflow/README

While the README could use a more thorough check and improvement, a typo in the main title got my attention, so I decided to fix it, as well as some other obvious typos, here and now.

Fix typos in dataflow README.

---

Utils/API/server/setup.sh

1. Added options:
```
-L, --log-dir DIR       directory for (application) log files
-R, --run-dir DIR       directory for .pid file
```
1. Short versions of directory-related options capitalized:
```
-C, --cfg-dir DIR       path to directory with configuration files used
by the application (absolute or relative to WWW_DIR)
-N, --nginx-dir DIR     Nginx home directory
```

API server setup improve

---

Utils/API/server/cgi-bin/dkb.fcgi
Utils/API/server/dkb.yaml.example
Utils/API/server/lib/dkb/api/__init__.py
Utils/API/server/lib/dkb/api/handlers.py
Utils/API/server/lib/dkb/api/storages/__init__.py
Utils/API/server/lib/dkb/api/storages/es.py
Utils/Elasticsearch/mapping/tasks.mapping

Method is available as `/task/kwsearch?kw=...`
Parameters:
* kw: single keyword (list of kwords is accepted as '?kw=...&kw=...')
* analysis: if analysis tasks should be searched (default: True)
* production: if production tasks should be searched (default: True)
* size: number of task documents in response (default: 2000)
* ds_size: max number of dataset documents returned for each task
(default: 20)
* timeout: request execution timeout (sec) (default: 120)

API/keywords: new API method for task search by keywords.

---

Utils/API/server/lib/dkb/api/storages/es.py

When `"all_fields": true` is used in `query_string` query, it analyzes
the string according to each field's analyzer (that's what we did it
for: to make sure that smth like "A14NNPDF23LO" from
"mc16_13TeV.303202.MadGraphPythia8EvtGen_A14NNPDF23LO_FRVZ_4LJ_mH800..."
can be used as a keyword). However when query string is "mc16_13tev",
for `taskname` field it is splitted into two tokens: "mc16" and "13tev".
And default operator is..."OR". So if "13tev" matches, ES won't care if
there's nothing about "mc16". Which is absolutely not what we're looking
for.
So -- the default operator is changed to "AND".

API/kwsearch: fix issue with incorrect results for kw like "mc16_13tev".

---

Utils/API/server/lib/dkb/api/__init__.py
Utils/API/server/setup.sh

Fixes:
* missed `APP_USER=<username>` in saved configuration;
* numerous error messages with `chown $APP_USER:$NGINX_GROUP`;
* wrong group ownership and permissions of `$SOCK_DIR` in some cases;
* Python versions conformity.
Changes:
* Python 2.7 is required now.
---
_Tested on aiatlas172_

API: setup fix

---

Utils/Dataflow/019_esFormat/esFormat.php
Utils/Elasticsearch/mapping/README
Utils/Elasticsearch/mapping/tasks.mapping

Information about message (in)completeness is, basically, some service information for this stage.
Currently it was decided to simply keep in the ES some service field that will allow to mark "incomplete" documents; later we will use it to estimate, how many records are affected on a regular basis, and decide what to do: allow "update" operation when we know we don't have the full document, but still want new information in the storage, or something else.
So Stage 19 now turns `_incomplete` field of the input message to the `update_required` ES field, and tries not to do something stupid about it (e.g. not to mark all record as "incomplete" when all we wanted was to update information from one specific external source).
ES mapping is updated accordingly.
**Question**: shouldn\`t the ES …

DF/019: "incomplete" messages handling (ES updates, pt.1.2).

---

Utils/Dataflow/025_chicagoES/stage.py

For some reason "taskid" and "jeditaskid" are not always the same: e.g.
there are plenty of jobs with taskid==2 and jeditaskid!=2.

DF/025: fix ES query (taskid -> jeditaskid).

---

Utils/Dataflow/069_upload2es/load_data.sh

`curl -sS` == `curl --silent --show-error`
These options will prevent cURL from showing progress, yet allow error
messages in case of failure.

DF/069: make data load more silent.

---

Utils/Dataflow/025_chicagoES/stage.py

At some point doc_type in the UC ES indices `jobs_archive_*` has changed, and now it is "_doc" (the default one, like "no specific type").
Same seem to come for the `tasks_archive_*` at some point.
There's no documents with `toths06_failed` field (based on the jobs data) in the DKB ES after `03-02-20 12:31:40`; and in UC ES for now there's available only jobs since `2019-11-13T00:00:01.000Z` (at least via Search API).
After this fix we should re-integrate missed data, but should be careful not to remove what we can't recover.

DF/025: fix ES queries (doc_type changed).

---

Utils/Dataflow/025_chicagoES/stage.py

Previously it was done only for the finished ones -- it was the part
of the task description provided by M.Borodin (since originally it was
supposed that we take this information from BigPanDA that would not be
happy if we queried it every now and again).
Now we're gonna get this information for all tasks: whatever's its
state, if there are some jobs -- we can get some useful data.

DF/025: allow CPU usage calculation for all tasks.

---

Utils/API/server/lib/dkb/api/__init__.py
Utils/API/server/lib/dkb/api/handlers.py
Utils/API/server/lib/dkb/api/storages/__init__.py
Utils/API/server/lib/dkb/api/storages/es.py
Utils/API/server/lib/dkb/api/storages/es/query/campaign-stat

Added new API method: `campaign/stat`.
The method accepts following parameters:
* `?htag=...&htag=...` -- hashtag (or number of hashtags); for statistics will be selected all tasks marked with at least one of the passed hashtags (logical `OR`).
Example URL: http://aiatlas172:5080/campaign/stat?htag=newfastcalosimntuponly&pretty
JSON response has following format *(field `errors` may be omitted if no error has occured)*:
```
{
status: <OK/failed>,
took_storage_ms: <storage query execution time in ms>,
total: <total number of matching tasks>,
errors: [..., <error message>, ...],
data: {
'tasks_processing_summary': {
<step>: {<status>: <n_tasks>, ...},
...
},
'overall_events_processing_summary': {
<step>: {
'input': <n_events>,
'output': <n_events>,
'ratio': <output>/<input>
},
...
}, …
```

API: add new method (campaign/stat).

---

Utils/Dataflow/019_esFormat/esFormat.php

Sub-PR from #292 
---
Current script can produce an action JSON in form
{"update":{...}, "index":{"_parent":...}} which makes no sense. This occurs
when the input JSON contains "_update" set to true and "_parent" set to
anything. Probably missed instance of "index" that should have been changed
to "$act" when the latter was introduced.
---
This commit is moved to a separate PR for it affects the integration process management and we need it in `master` ASAP.

DF/019: Fix error with update and index in same action.

---

Utils/API/server/lib/dkb/api/__init__.py
Utils/API/server/lib/dkb/api/storages/__init__.py
Utils/API/server/lib/dkb/api/storages/es.py
Utils/API/server/lib/dkb/api/storages/es/query/campaign-stat

New fields in the method response:
* `data['last_update']` -- last registered timestamp for selected tasks;
* `data['date_format']` -- format for datetime fields parsing (in terms of Python `datetime` module);
* `data[<step>]['start'] -- earliest `start_time` for given step;
* `data[<step>]['end'] -- latest `end_time` for given step.

API/campaign_stat: add steps timing info.

---

Utils/API/server/lib/dkb/api/__init__.py
Utils/API/server/lib/dkb/api/handlers.py
Utils/API/server/lib/dkb/api/storages/__init__.py
Utils/API/server/lib/dkb/api/storages/es.py
Utils/API/server/lib/dkb/api/storages/es/query/campaign-stat

Main changes:
* new section in response: `data['events_24h']`;
* new parameter `events_src` to specify method to calculate output events number.
---
With the new option can be altered valued of the following fields:
* data['overall_events_processing_summary'][<step>]['output'];
* data['events_24h'][<step>].
Parameter `events_src` accepts values:
* `'ds'` -- use output datasets version (same as before) (default);
* `'task'` -- use `processed_events`;
* `'all'`  -- provide all possible values as hash.
Response format (with `events_src` set to `'ds'` or `'task'`):
```
{
took_storage_ms: <storage query execution time in ms>,
total: <total number of matching tasks>,
errors: [..., <error message>, ...],
data: {
last_update: <last_registered_task_timestamp>,
date_format: <datetime_format>, …
```

API/campaign_statistics: update

---

Utils/API/server/lib/dkb/api/__init__.py
Utils/API/server/lib/dkb/api/storages/es/query/campaign-stat

Previously was used value of `requested_events` field [1], now it is
`input_events` [2].
---
[1] `requested_events` is taken from `ATLAS_PANDA.JEDI_DATASETS.nevents`
of task's 'input' dataset
[2] `input_events` is taken as:
* for EVNT tasks:
* if defined `n_files_to_be_used` [3]:
`n_files_to_be_used * n_events_per_job / (n_files_per_job|1)`;
* if not defined `n_files_to_be_used`:
`processed_events`;
* for other tasks:
`min(requested_events, primary_input_events)`.
[3] Origins of values for `input_events` calculation:
* `n_files_to_be_used`: ATLAS_DEFT.T_PRODUCTION_TASK.nfilestobeused;
* `n_events_per_job`: JEDI task parameter `nEventsPerJob`;
* `n_files_per_job`: JEDI task parameter `nFilesPerJob` (if not
defined, will be taken as 1).

API/campaign_stat: improve input events calculation.

---

Utils/Elasticsearch/mapping/tasks.mapping

This mapping is the only place where the field name lacks "s" at the end.
Everywhere else - in Stage 009, data samples, DKB's ES - the other version
is used. I presume that this is a typo, and the actual mapping used in our
ES was "fine-tuned by a file" (or not touched at all, given how
ES's dynamic mapping works).

Fix a typo.

---

Utils/API/server/lib/dkb/api/__init__.py
Utils/API/server/lib/dkb/api/handlers.py
Utils/API/server/lib/dkb/api/storages/__init__.py
Utils/API/server/lib/dkb/api/storages/es.py

Method `/task/stat` is renamed to `/step/stat`.
The method was not announced to anyone yet, so it is OK to change its name without second thought about backward compatibility.

API: rename `task/stat` to `step/stat`.

---

Utils/API/server/lib/dkb/api/__init__.py
Utils/API/server/lib/dkb/api/storages/es.py

Remove warning about excluded data formats in case of 'step' steps ('cause resulting data are not based on data formats).

API: fix step stat warning

---

Utils/API/server/lib/dkb/api/__init__.py
Utils/API/server/lib/dkb/api/storages/es/transform.py

When `percent_done` is too close to 100% it may accidently be rounded to
100%, marking step as "fully completed" -- even if it is not. To avoid
this situation, the value is artificially set to 99.99% if we know for
sure that number of already processed events is less than that of
required/input/expected ones.
Original commit:
PanDAWMS/panda-bigmon-atlas@fe9a65e

API: add adjustment for `percent_done`.

---

Utils/Dataflow/test/pyDKB/case/20/err
Utils/Dataflow/test/pyDKB/case/21/err
Utils/Dataflow/test/pyDKB/test.sh

When pyDKB code is updated, some test cases that contain traceback info
in the expected STDERR, can be broken. From now on all ', line XXX' parts
of these tracebacks in the `case/*/err` can (and should) be written as
', line <NNN>' -- this way, the real line numbers are hidden and their
changes won't affect the test cases.

pyDKB/test: test line numbers

---

Utils/API/server/lib/dkb/api/__init__.py
Utils/API/server/lib/dkb/api/handlers.py
Utils/API/server/lib/dkb/api/storages/es/query/campaign-stat-step-aggs
Utils/API/server/lib/dkb/api/storages/es/transform.py

"Daily progress" is not "last day's progress", but "day-by-day
progress". So the method's output data format has changed: instead of
'events_24h' there's now 'events_daily_progress' sections, with data in
the following form:
```
{
...
"data": {
...
"events_daily_progress": {
<step_name>: {
<date>: <n_events_processed_by_tasks_finished_'today'>,
...
},
...
}
}
}
```
Value for `<n_events_processed_by_tasks_finished_'today'>` is calculated
as sum of output events of all tasks with "end_date" within given day's
interval (from <date> 00:00:00 to <date> 23:59:59) and with status
'done' or 'finised'.
Output events, as in other cases for this method, can be calculated
basing on the task's "processed_events" field, or on the number of
events in the task's (not removed) output datasets (see …

API/campaign_stat: events daily progress.

---

.travis.yml
Tests/travis/pyDKB.sh
Utils/Dataflow/test/pyDKB/test.sh

We have test script for pyDKB, but we should run it manually.
TravisCI may do it instead of us.
Fix #351

Run pyDKB check in TravisCI

---

Tests/travis/functions.sh

We are useing getLinesFromFile for collecting wrong lines from files in commit/PR.
This funtion use grep to collect all bad strings.
As a default grep assumes that regular expression will be used for search,
but we are actually searching strings that looks exactly as target string.
So we should search not regular expression, but fixed string.
Fix #349

travis functions (fix): collect lines from files as fixed strigns

---

Utils/Dataflow/069_upload2es/load_data.sh

Changes:
* input data verification (to check at least that NDJSON consists of JSONs);
* ES bulk API response parsing:
* to have information on failed load attempts;
* to know how many records were loaded (bulk API may simply skip records with broken `action` string).

DF/069: error logging

---

Utils/API/server/lib/dkb/api/__init__.py
Utils/API/server/lib/dkb/api/storages/es/methods.py
Utils/API/server/lib/dkb/api/storages/es/query/campaign-stat-step-aggs
Utils/API/server/lib/dkb/api/storages/es/transform.py

Fixed:
* error handling (now "parsing" errors are distinguished from "query execution" ones more clearly);
* unhandled division by zero;
* 'input_events' calculation logic (only "valid" tasks are taken into account).
Example of the difference in the response -- before and after the last fix
(`?htag=mc16e_pa&events_src=task`):
```
"Evgen Merge": {                │  "Evgen Merge": {
"input": 361333334.0,         │    "input": 354115246.0,
"ratio": 0.9800237417342735,  │    "ratio": 1.0,
"output": 354115246.0         │    "output": 354115246.0
},                              |  },
```

API/campaign_stat: bug and logic fixes.

---

Utils/Dataflow/009_oracleConnector/Oracle2JSON.py
Utils/Dataflow/071_esConsistency/consistency.py
Utils/Dataflow/pyDKB/common/misc.py

Some ambiguous variables were detected by Travis in #309. Code and/or Travis should be checked further, if possible - since these reports only appeared now, and all 3 of them are about "l", maybe some different problematic variables still exist.

Fix ambiguous variables.

---

Utils/Dataflow/019_esFormat/esFormat.php
Utils/Elasticsearch/config/es.example

For now it is pretty much hardcoded: stage 019 (esFormat), that prepares data for upload, is only aware of 2 indices: "tasks" (for tasks metadata) and "progress" (for tasks processing progress metadata). If no index specified in the input data, "tasks" index is used.
There's also a "default" index -- it will be used if a desired index is not configured in the provided (or default) config file.
It may be improved later, e.g. when PHP script starts reading the configuration INI file by itself -- but for now that's enough.
ES configuration file previously contained only one index name ("ES_INDEX" variable); it is used by multiple stages so it is left in the config file to keep existing functionality. It can not be set to the
"value of ES_INDEX_TASKS" like this:
ES_INDEX=$ES_INDEX_TASKS …

DF: allow single dataflow writing to two different ES indices.

---

Utils/Dataflow/069_upload2es/load_data.sh
Utils/Dataflow/run/data4es-start

If JSON contains symbols like '*', in `echo $line` they will be interpreted by Shell and turned into (e.g.) a list of local files and subdirectories. Which may contain invalid (from the JSON syntax point of view) characters/ESC sequences, like '\ '.
---
The issue had effect, for example, for tasks from production request 31979 (e.g. taskid: 21835493, 21834893).

DF/data4es: fix issue with invalid ESC characters in JSON.

---

Utils/Elasticsearch/requests/campaign-stat-jq-parser
Utils/Elasticsearch/requests/campaign-stat-q.json
Utils/Elasticsearch/requests/campaign-stat-r-parsed.json
Utils/Elasticsearch/requests/campaign-stat-r.json

Example files:
*  `*-q.json`  -- ES query example
*  `*-jq-parser`  -- parsing instructions for command-line JSON processor `jq`
*  `*-r.json` -- ES response
*  `*-r-parsed.json` -- ES response, parsed with `jq`
Command-line instructions:
* to execute the query:
```
curl -u <user>:<passwd> \
-X GET 'http://aiatlas171.cern.ch:9200' \
-H 'Content-type: application/json' \
-d @campaign-stat-q.json \
| less
```
* to parse query results with `jq`:
```
curl <...> \
| jq -f campaign-stat-jq-parser \
| less
```

ES/queries: add query example for campaign statistics.

---

Utils/Dataflow/data4es/091_datasetsRucio/datasets_processing.py

Split `extract_scope()` in two functions: specific operation for dealing with composite dataset names and more generic scope extraction.

091 scope functions rework

---

Utils/Dataflow/data4es/019_esFormat/run.sh

...that was broken after #361 (DF directory layout change).

DF/data4es/019: fix default ES config path.

---

Utils/Dataflow/data4es-nested/025_chicagoES/require
Utils/Dataflow/data4es-nested/025_chicagoES/stage.py
Utils/Dataflow/data4es/025_chicagoES/require
Utils/Dataflow/data4es/025_chicagoES/stage.py

'atlas-kibana.mwt2.org' is the main interface host, and since recently
it uses HTTPS instead of HTTP; so we switch our stage from previous
configuration (with requests to data nodes) to the more official one.

DF/data4es(-nested)/025: change Chicago ES hosts configuration.

---

Utils/Dataflow/data4es-nested/025_chicagoES/stage.py
Utils/Dataflow/data4es/025_chicagoES/stage.py

1. Not only jobs indices (`jobs_srchive_YYYY-mm-dd`), but also tasks indices (`tasks_archive_YYYY`) are taken with date index if it is possible.
2. If task's `end_time` is not defined, it is taken as current datetime: this way for recent tasks that do not have `end_time` yet, but in fact were started just yesterday or so, we query more or less short list of indices instead of `jobs_archive_*` (and `tasks_archive_*`).

DF/data4es(-nested)/025: more precise indices definition.

---

Utils/Dataflow/data4es-nested/019_esFormat/run.sh
Utils/Dataflow/data4es-nested/069_upload2es/load_data.sh
Utils/Dataflow/data4es-nested/run/data4es-consistency-check
Utils/Dataflow/data4es/069_upload2es/load_data.sh
Utils/Dataflow/data4es/run/data4es-consistency-check

The path was broken in 70bb8e9 and was only fixed in a couple of places
instead of all the affected files.

DF/*: fix path to default ES config (again).

---

Utils/Dataflow/shell_lib/run_stage

Each STDERR line is now prefixed with source stage's ID:
(ID) <original stderr line>
Example of log after this PR:
```
(INFO) 28-08-2020 13:50:09 (data4es) Stage 19 set to update mode.
(INFO) 28-08-2020 13:50:09 (data4es) Starting process.
(17) 2020-08-28 13:50:09 (WARN) (pyDKB.dataflow.cds) Submodule failed (No module named invenio_client.contrib)
(09) (INFO) Stage 009 configuration (/home/dkb/dkb-dev.git/Utils/Dataflow/data4es/config/009.cfg):
(09) (INFO) ---
(09) (INFO)  step_seconds : '86400'
(09) (INFO)  initial_date : '2020-08-27 11:00:00'
(09) (INFO)  timestamp_tz : 'UTC'
(09) (INFO)  offset_file  : '/home/dkb/dkb-dev.git/Utils/Dataflow/data4es/config/.offset'
(09) (INFO)  delay        : '0'
(09) (INFO)  mode         : 'SQUASH'
(09) (INFO)  queries      : '{'tasks': {'params': …
```

DF/run_stage: add stage ID as prefix to stage's stderr lines.

---

Utils/Dataflow/data4es-nested/025_chicagoES/stage.py
Utils/Dataflow/data4es/025_chicagoES/stage.py

The logic about how to get the list of indices was a bit wierd.
Now it is as follows:
* list of indices is combined from index names generated for set of  time points;
* index name is prefix + datetime suffix, taken at given time point;
* set of time points is from task's beginnig till the tasks's end with step matching (shortest) interval between two successive index names:
* 1 day (eg for '*_2020-01-24' and '*_2020-01-25');
* 28 days (eg for '*_2020-02*' and '*_2020-03*');
* 365 days (eg for '*_2019' and '*_2020');
* task's end is always used to produce one more index name (so it does not matter if the last time point was in the same index or in the previous one -- it will be added anyway).
This way all indices starting from the one containing task's beginning to the one containing …

DF/data4es(-nested)/025: fix indices names definition.

---

Utils/Dataflow/data4es-nested/017_adjustMetadata/adjustMetadata.py
Utils/Dataflow/data4es/017_adjustMetadata/adjustMetadata.py

Explicitly specified NULL value led to the following error in the DF process:
```
(17) 2020-09-13 05:06:10 (ERROR) (ProcessorStage) sequence item 1: expected string or Unicode, NoneType found
(17) 2020-09-13 05:06:10 (DEBUG) (ProcessorStage) Traceback (most recent call last):
(17) (==)   File <...>, line 399, in process
(17) (==)     generate_step_names(data)
(17) (==)   File <...>, line 348, in generate_step_names
(17) (==)     data['ami_tags_format_step'].append(':'.join([tags, data_format]))
(17) (==) TypeError: sequence item 1: expected string or Unicode, NoneType found
```

DF/data4es(-nested)/017: fix issue with NULL value of "output_formats".

---

Utils/Dataflow/data4es-nested/095_datasetInfoAMI/amiDatasets.py
Utils/Dataflow/data4es/095_datasetInfoAMI/amiDatasets.py

Without this retry the stage fails sometimes like this:
(ERROR) Test command ListCommands failed. Are you sure you have a
valid certificate?
(==) Exception: pyAMI exception: could not connect to
`https://ami.in2p3.fr:443/AMI/servlet/net.hep.atlas.Database.Bookkeeping.AMI.Servlet.FrontEnd`:
[Errno 111] Connection refused
It seems to happen due to some issues at the AMI server side, but those are usually short-time ones, so a retry after a while is very likely to be successful.

DF/data4es(-nested)/095: retry 'ListCommands' on client initialisation.

---

Utils/Dataflow/data4es-nested/095_datasetInfoAMI/amiDatasets.py
Utils/Dataflow/data4es/095_datasetInfoAMI/amiDatasets.py

Endpoints (see `pyAMI/atlas/__init__.py`):
- 'atlas': 'https://ami.in2p3.fr:443/AMI/servlet/net.hep.atlas.Database.Bookkeeping.AMI.Servlet.FrontEnd'
- 'atlas-replica': 'https://atlas-ami.cern.ch:443/AMI/servlet/net.hep.atlas.Database.Bookkeeping.AMI.Servlet.FrontEnd'
It is said that CERN replica is less loaded while have same data.
Endpoints passed to `pyAMI.client.Client()` are used one after another in `execute()` until succsess, so after this change client will first query the CERN instance and then, in case of any problem, fall back to the main 'atlas' instance in France.

DF/data4es(-nested)/095: use CERN instance of AMI.

---

Utils/Dataflow/data4es-nested/091_datasetsRucio/datasets_processing.py

`stage.log` used in a function where `stage` isn't defined.
Fixes issue:
```
(91) 2020-10-02 03:50:28 (ERROR) (ProcessorStage) global name 'stage' is not defined
(91) 2020-10-02 03:50:28 (DEBUG) (ProcessorStage) Traceback (most recent call last):
(91) (==)   File "/home/dkb/dkb-test.git/Utils/Dataflow/data4es-nested/091_datasetsRucio/../pyDKB/dataflow/stage/ProcessorStage.py", line 255, in run
(91) (==)     if msg and process(self, msg):
(91) (==)   File "/home/dkb/dkb-test.git/Utils/Dataflow/data4es-nested/run/../091_datasetsRucio/datasets_processing.py", line 162, in process
(91) (==)     output_ds = process_ds(data.get(SRC_FIELD[OUTPUT]), OUTPUT)
(91) (==)   File "/home/dkb/dkb-test.git/Utils/Dataflow/data4es-nested/run/../091_datasetsRucio/datasets_processing.py", line 212, in …
```

DF/data4es-nested/091: bug fix.

---

Utils/API/server/lib/dkb/api/__init__.py
Utils/API/server/lib/dkb/api/handlers.py

Minor changes:
* nested endpoint methods' results are accompanied with a warning
message regarding incompleteness of data in ES indices.
---
NOTE: the warning appears in any method's response, even if it is `/info` method that has nothing to do with ES indices. But I guess it's fine: better to be warned before using any of the methods listed in the `/info` response...

API: nested warning.

---

Utils/Dataflow/data4es-nested/095_datasetInfoAMI/amiDatasets.py
Utils/Dataflow/data4es/095_datasetInfoAMI/amiDatasets.py

The operation `change_key_names()` makes no sence in case when there was
any exception; so placing it after `try/except` clause just "as is"
looks a bit wierd.
Placing it into `else` section of `try/except` says: "and if
everything's fine we need to do this thing". This looks better.

DF/data4es(-nested)/095: improve try/except logic.

---

Utils/Dataflow/data4es-nested/095_datasetInfoAMI/amiDatasets.py
Utils/Dataflow/data4es/095_datasetInfoAMI/amiDatasets.py

Sometimes AMI response is not a JSON object, and stage fails to parse it as JSON:
```
(95) 2020-11-22 22:10:24 (DEBUG) (ProcessorStage) Traceback (most recent call last):
(95) (==)   File "/home/dkb/dkb-test.git/Utils/Dataflow/data4es/run/../095_datasetInfoAMI/amiDatasets.py", line 167, in process
(95) (==)     amiPhysValues(data)
(95) (==)   File "/home/dkb/dkb-test.git/Utils/Dataflow/data4es/run/../095_datasetInfoAMI/amiDatasets.py", line 203, in amiPhysValues
(95) (==)     json_str = json.loads(res)
(95) (==)   File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
(95) (==)     return _default_decoder.decode(s)
(95) (==)   File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
(95) (==)     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
(95) (==)   File …
```

DF/data4es(-nested)/095: improve invalid AMI response handling.

---

Utils/Dataflow/data4es-nested/095_datasetInfoAMI/amiDatasets.py

Any error occured when the stage tries to get additional metadata from AMI is not a critical error; so it's better to be output as 'WARN', not 'ERROR'+traceback.
Currently log messages look like these
```
2021-03-19 14:26:07 (WARN) (ProcessorStage) Failed to process dataset 'mc16_13TeV.346806.MadGraphPythia8EvtGen_A14NNPDF23LO_RS_G_ZZ_llll_c10_m0200.simul.HITS.e7972_e5984_s3126_tid20330292_0
0'
(==) Reason: Non-JSON AMI response: u'AMI#\ncommand : AMIGetPhysicsParamsForDataset\ntime    : 2021-03-19  at 02:26:07 PM CET\nresult  : \n  -> rowset\n#'
```
```
2021-03-19 14:25:48 (WARN) (ProcessorStage) Failed to process dataset 'mc16_13TeV.346806.MadGraphPythia8EvtGen_A14NNPDF23LO_RS_G_ZZ_llll_c10_m0200.simul.HITS.e7972_e5984_s3126_tid20330292_0
0'
(==) Reason: Unexpected AMI response: …
```

DF: improve AMI error logging

---

Utils/Dataflow/data4es-nested/run/data4es-start

`data4es-start` wouldn't pass to stage 025 (Chicago ES) path to the
config file from the common config directory; insted, the stage used the
default config file from `025_chicagoES/../config/025.cfg`.

fix(DF/config): pass proper config file to stage 025

---

Utils/Dataflow/data4es/069_upload2es/load_data.sh
Utils/Dataflow/data4es/071_esConsistency/consistency.py
Utils/Elasticsearch/config/es.example
Utils/Elasticsearch/tools/load_mapping.sh
Utils/Elasticsearch/tools/search.sh

Add ES config parameters:
- `ES_PATH` (to allow endpoints like `host:port/path`, not only `host:port/`);
- `ES_PROTO` (to allow not only HTTP, but also HTTPS (or whatever specified) protocol for ES connections);
- `ES_CA_CERTS` (for Python client in consistency check only; `curl` seem to find path to certs by itself, so the usage of parametric value is not required right now).
Affected:
- `Utils/Elasticsearch/tools` (`load_mapping` and `search`);
- `Utils/Dataflow/data4es/069_upload2es` (`data4es` process stage),
- `Utils/Dataflow/data4es/071_consistency` (consistency check process stage).
------
The default behavior must not have changed for the default settings are kept as they were hard-coded originally

feat(config): more ES access params

---

Utils/Dataflow/data4es/071_esConsistency/consistency.py
Utils/Elasticsearch/config/es.example

Remove config parameter `ES_INDEX`, which was "left for backwards compatibility".
Feels like only Stage071 (consistency checker) used to rely on this one.

Unify es index config

---

Utils/Dataflow/data4es/071_esConsistency/consistency.py

Now consistency check must work properly (with both old and actual versions, if it matters).

fix(consistency): missed ES `_type` in data flow

---

.github/workflows/build_almalinux_9_docker.yaml
Installation/Docker/AL9/Dockerfile
Installation/Docker/AL9/httpclient.py

Add Dockerfile and configs to build DKB docker image for AlmaLinux9

Docker build
